version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Artiside-frontend
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ec2-user/Artiside-frontend/aws/scripts
    pattern: '*.sh'
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  ApplicationStop:
    - location: aws/scripts/application-stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: aws/scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws/scripts/after-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws/scripts/application-start.sh
      timeout: 300
      runas: root
